apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-fastapi-app-ingress
spec:
  rules:
  - host: my-fastapi-app.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-fastapi-app-service
            port:
              number: 80